#!/bin/bash
set -e

ME=$(basename "$0")

##
# Stop/start a WordPress instance
# Stop or start a WordPress instance by changing the 'Active' parameter on the CloudFormation stack.
##

USAGE="Stop/start a WordPress instance.

Usage:
  $ME <app> <env>

Parameters:
  <app>      Name of the application.
  <env>      The environment to connect to [dev|staging]

Example usage:
  $ME myappname dev
"

if [ -z $1 ] || [ -z $2 ]; then
	echo "$USAGE"
	exit 1
fi

if [[ $0 =~ "stop" ]]; then
	ACTIVE="false"
else
	ACTIVE="true"
fi

APP_NAME=$1
ENVIROMENT=$2

if [ "$ENVIROMENT" != "dev" ] && [ "$ENVIROMENT" != "staging" ]; then
	echo "Invalid <env> value. Allowed values: dev, staging"
	exit 1
fi

PARAMS=`aws cloudformation get-template-summary --stack-name "$APP_NAME-$ENVIROMENT" --output text --query "Parameters[*].ParameterKey"`

CF_PARAMS=""

for PARAM in $PARAMS; do
	if [ $PARAM = 'Active' ]; then
		CF_PARAMS="$CF_PARAMS ParameterKey=$PARAM,ParameterValue=$ACTIVE"
	else
		CF_PARAMS="$CF_PARAMS ParameterKey=$PARAM,UsePreviousValue=true"
	fi
done

aws cloudformation update-stack --stack-name "$APP_NAME-$ENVIROMENT" --use-previous-template --parameters $CF_PARAMS --capabilities CAPABILITY_IAM
